name: "Rahven's L'ukulele"
favicon: null
layout_spectrum: 0.1765957
typography_spectrum: 0.3468085
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFEFF'
    - '#301B1A'
    - '#929CA6'
    - '#FF4427'
    - '#F9B8A0'
  brandStrength: 0.5
  lightness: 0.9375
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
